version: '3.1'

services:
  app:
    build: . 
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - .:/api
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
       - 5432:5432


